[unstable]
codegen-backend = true

[profile.release]
lto = true
strip = true
codegen-units = 1
panic = "abort"
opt-level = "z"

[profile.release.package."*"]
strip = true
opt-level = 3

[target.'cfg(all())']
rustflags = [
  # nightly
  "-Zunstable-options",
  "-Zshare-generics=y",
  "-Ctarget-cpu=native",
  "-Zthreads=16",

  # stable
  "-Wclippy::all",
  "-Fdeprecated",
  "-Fredundant-imports",
  "-Ffuture-incompatible",
  "-Fmissing-unsafe-on-extern",
  "-Fdeprecated-in-future",
  "-Fdeprecated-safe-2024",
  "-Frust-2024-compatibility",
]
